### ISSUE TITLE
Problema con la generación de Programa del Barça

### ISSUE THREAD

**Issue by cesaralba** [cesaralba/jimenezIntelligence#232]
Creo que el problema viene de un Junior que no ha jugado pero figura en la plantilla. No tengo claro de dónde se sacan los datos.

Datos de Ref: /home/LIVE/SuperManager/temporada/LACB2024.202412291924.p.gz

~~~
Traceback (most recent call last):
  File "/home/calba/Dropbox/devel/jimenezIntelligence/./bin/generaPrograma.py", line 134, in <module>
    main(argsCLI)
    ~~~~^^^^^^^^^
  File "/home/calba/Dropbox/devel/jimenezIntelligence/./bin/generaPrograma.py", line 129, in main
    preparaLibro(args.outfile, tempData, datosSig)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/calba/Dropbox/devel/jimenezIntelligence/./bin/generaPrograma.py", line 63, in preparaLibro
    infoJugadores = paginasJugadores(tempData, datosSig.abrevLV, datosSig.jugLocal, datosSig.jugVis)
  File "/home/calba/Dropbox/devel/jimenezIntelligence/SMACB/Programa.py", line 774, in paginasJugadores
    tablasJugadVisit = tablasJugadoresEquipo(datosVisit, abrev=abrEqs[1])
  File "/home/calba/Dropbox/devel/jimenezIntelligence/SMACB/Programa.py", line 969, in tablasJugadoresEquipo
    t = auxGeneraTablaJugs(auxDF, claveTabla, infoTabla, INFOTABLAJUGS, baseOPS, FORMATOCAMPOS, ANCHOLETRA,
                           repeatRows=1, abrev=abrev)
  File "/home/calba/Dropbox/devel/jimenezIntelligence/SMACB/Programa.py", line 466, in auxGeneraTablaJugs
    newCol = dfDatos[level].apply(colSpec['generador'], axis=1) if 'generador' in colSpec else dfDatos[[col]]
             ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/devel/PyENVs/SACBenv/lib64/python3.13/site-packages/pandas/core/frame.py", line 10374, in apply
    return op.apply().__finalize__(self, method="apply")
           ~~~~~~~~^^
  File "/home/devel/PyENVs/SACBenv/lib64/python3.13/site-packages/pandas/core/apply.py", line 916, in apply
    return self.apply_standard()
           ~~~~~~~~~~~~~~~~~~~^^
  File "/home/devel/PyENVs/SACBenv/lib64/python3.13/site-packages/pandas/core/apply.py", line 1063, in apply_standard
    results, res_index = self.apply_series_generator()
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/devel/PyENVs/SACBenv/lib64/python3.13/site-packages/pandas/core/apply.py", line 1081, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
                 ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/calba/Dropbox/devel/jimenezIntelligence/SMACB/Programa.py", line 93, in <lambda>
    return lambda f: auxKeyDorsal(f, *kargs, **kwargs)
                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/home/calba/Dropbox/devel/jimenezIntelligence/SMACB/Programa.py", line 370, in auxKeyDorsal
    result = -1 if dato == "00" else int(dato)
                                     ~~~^^^^^^
ValueError: cannot convert float NaN to integer
~~~

**Comment by cesaralba** [comment]
Sospecho que con el mergeo de #231 la cosa se va a extender a todos. Veremos
